
[font]
size=11.0
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular"  }

[window]
padding = { x = 6, y = 6 }
dimensions = { lines = 30, columns = 115 }

[cursor]
style = { shape = "beam", blinking = "off" }

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_mod.toml"
]

