#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore & ./.config/polybar/polybar-bspwm.sh & xremap .config/xremap/xremap.yml & picom & xsetroot -cursor_name left_ptr &


bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#9cd9fc"
